# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\asus\coding\python\osu_player\resources\SettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 310)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ignore_case_checkbox = QtWidgets.QCheckBox(Dialog)
        self.ignore_case_checkbox.setChecked(True)
        self.ignore_case_checkbox.setObjectName("ignore_case_checkbox")
        self.verticalLayout.addWidget(self.ignore_case_checkbox)
        self.seed_label = QtWidgets.QLabel(Dialog)
        self.seed_label.setObjectName("seed_label")
        self.verticalLayout.addWidget(self.seed_label)
        self.seed_lineedit = QtWidgets.QLineEdit(Dialog)
        self.seed_lineedit.setObjectName("seed_lineedit")
        self.verticalLayout.addWidget(self.seed_lineedit)
        self.format_label = QtWidgets.QLabel(Dialog)
        self.format_label.setObjectName("format_label")
        self.verticalLayout.addWidget(self.format_label)
        self.format_textedit = QtWidgets.QPlainTextEdit(Dialog)
        self.format_textedit.setObjectName("format_textedit")
        self.verticalLayout.addWidget(self.format_textedit)
        self.change_beatmap_dir_pushbutton = QtWidgets.QPushButton(Dialog)
        self.change_beatmap_dir_pushbutton.setObjectName("change_beatmap_dir_pushbutton")
        self.verticalLayout.addWidget(self.change_beatmap_dir_pushbutton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.ignore_case_checkbox.setText(_translate("Dialog", "Ignore upper/lower case in search"))
        self.seed_label.setText(_translate("Dialog", "Set random seed"))
        self.format_label.setText(_translate("Dialog", "Song info format"))
        self.format_textedit.setPlainText(_translate("Dialog", "{artist_unicode} - {title_unicode}"))
        self.change_beatmap_dir_pushbutton.setText(_translate("Dialog", "Browse Songs directory"))
